// front/src/components/Menu.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <router-link class="navbar-brand" to="/">MoneyControl</router-link>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <router-link class="nav-link" :to="current">Opérations du mois<span
                            class="sr-only">(current)</span>
                    </router-link>
                </li>
                <li class="nav-item">
                    <router-link class="nav-link" to="/unclassifiedoperations">Opérations non
                        classées
                    </router-link>
                </li>
                <li class="nav-item">
                    <router-link class="nav-link" to="/operationsupload">Charger un fichier
                    </router-link>
                </li>
                <li class="nav-item">
                    <router-link class="nav-link" to="/rules">Règles</router-link>
                </li>
            </ul>
        </div>
    </nav>
</template>

<script>
    import moment from 'moment';

    export default {
        name: "Menu",

        data: function () {
            return {
                current: this.build_path()
            }

        },
        methods: {
            build_path() {
                let current_month = moment().month() + 1;
                return "/operations/" + moment().year() + "/" + current_month;
            }

            // gogo() {
            //     this.$router.push({name: 'operations', params: {year: 2019, month: 9}})
            // }

        }
    };
</script>

<style lang="sass">
    li
        .router-link-exact-active
            color: #42b983 !important

</style>

// client/src/app/menu/menu.component.ts
import {Component, OnInit} from '@angular/core';
import * as moment from 'moment';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.sass']
})
export class MenuComponent implements OnInit {

  navbarCollapsed = true;

  year: string;
  month: number;

  constructor() {

  }

  ngOnInit() {
    this.year = moment().format('YYYY');
    this.month = +moment().format('MM');
  }

  toggleNavbar() {
    this.navbarCollapsed = !this.navbarCollapsed;
  }

}


<!--<nav class="navbar navbar-light navbar-toggleable-md fixed-top bg-faded">-->
<!--<button type="button" class="navbar-toggler navbar-toggler-right" (click)="toggleNavbar()">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<!--<a class="navbar-brand">MoneyControl</a>-->
<!--<div id="navbar" class="navbar-collapse" [class.collapse]="navbarCollapsed">-->
<!--<div class="nav navbar-nav mr-auto">-->
<!--<a class="nav-item nav-link">Operations</a>-->
<!--</div>-->
<!--</div>-->
<!--</nav>-->


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="" routerLink="/">MoneyControl</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="" routerLink="/operations">Toutes Op&eacute;rations</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="" routerLink="/operations" [queryParams]="{ year: 2018,month:5 }">
          Op&eacute;rations du mois
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="" routerLink="/operations"
           [queryParams]="{ category: 'unclassified' }">Op&eacute;rations non classées
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="" routerLink="">Charger un fichier</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="" routerLink="/rules">Règles</a>
      </li>

    </ul>
  </div>
</nav>
